logging:
  level:
    root: debug
spring:
  rabbitmq:
    host: 10.2.41.73
    username: bd_test
    password: bd_test
    virtual-host: budget_test1
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  zipkin:
#    base-url: http://localhost:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  cloud:
    sentinel:
      transport:
        port: 8012
        dashboard: localhost:8080
    gateway:
#      globalcors:
#      '[/**]':
#        allowed-origins: "*"
#        allowed-headers: "*"
#        allow-credentials: true
#        allowed-methods:
#          - GET
#          - POST
#          - DELETE
#          - PUT
#          - OPTION
      routes:
        - id: url-proxy-baidu
          uri: https://www.baidu.com
          filters:
            - RewritePath=/baidu,/
          predicates:
            - Path=/baidu
        - id: serviceProvider-router
          uri: lb://serviceProvider
          filters:
            - RewritePath=/serviceProvider,/
          predicates:
            - Path=/serviceProvider/**
        - id: serviceConsumer-router
          uri: lb://serviceConsumer
          filters:
            - RewritePath=/serviceConsumer,/
          predicates:
            - Path=/serviceConsumer/**
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: \${spring.cloud.client.ip-address}:\${spring.application.name}:\${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  versin: ${version}
  name: ${rootProject.name}
  group: ${group}
  author: wangxing
  blog: https://wangxing.blog.csdn.net